### ISSUE TITLE
Docs for Either seem backwards

### ISSUE THREAD

**Issue by mmueller** [jdantonio/functional-ruby#31]
Unless I'm mistaken, the example for Either shows "left" holding a successful result and "right" holding an error value, which is the opposite of how they're described in the docs.

**Comment by jdantonio** [comment]
Looking at the code, the `#left` method has `#reason` [as an alias](https://github.com/jdantonio/functional-ruby/blob/master/lib/functional/either.rb#L104), indicating failure. The `#right` method has `#value` [as an alias](https://github.com/jdantonio/functional-ruby/blob/master/lib/functional/either.rb#L113), indicating success. So it appears that the example is wrong. I'll fix it.

**Comment by jdantonio** [comment]
Fixed [here](http://jerrydantonio.com/functional-ruby/Functional/Either.html).
